"use strict";

const ORIGIN = "OmaType original curated vocabulary";
var englishWords = "amber anchor apple april arch arrow atlas autumn bamboo beacon birch bloom blue brave breeze brick bright brook brush cabin cable calm canvas cedar".split(" ");
if (typeof module !== "undefined" && module.exports) englishWords = require("./words.js").slice();

function vocabulary(source) {
  const seen = {};
  return String(source).split(/\s+/).filter(function(token) {
    if (!token || seen[token]) return false;
    seen[token] = true;
    return true;
  });
}

function pack(id, label, source) {
  return {id: id, label: label, category: "programming", origin: ORIGIN, words: vocabulary(source)};
}

const PACKS = {
  english: {id: "english", label: "English", category: "natural", origin: ORIGIN, words: englishWords},
  ada: pack("ada", "Ada", "abort abs abstract accept access aliased all and array at begin body case constant declare delay delta digits do else elsif end entry exception exit for function generic goto if in interface is limited loop mod new not null of or others out overriding package pragma private procedure protected raise range record rem renames requeue return reverse select separate some subtype synchronized tagged task terminate then type until use when while with xor"),
  assembly: pack("assembly", "Assembly", "section global extern mov lea push pop call ret cmp test jmp je jne jg jge jl jle add sub mul imul div idiv inc dec and or xor not shl shr nop int syscall byte word dword qword rax rbx rcx rdx rsi rdi rsp rbp eax ebx ecx edx"),
  bash: pack("bash", "Bash", "alias bg bind break builtin case cd command continue declare do done echo elif else esac eval exec exit export false fi for function getopts hash help history if in jobs kill local printf pwd read readonly return select set shift source test then time trap true type typeset ulimit umask unalias unset until wait while $@ $? ${HOME} [[ ]]"),
  c: pack("c", "C", "auto break case char const continue default do double else enum extern float for goto if inline int long register restrict return short signed sizeof static struct switch typedef union unsigned void volatile while _Atomic _Bool _Complex _Generic _Imaginary _Noreturn _Static_assert _Thread_local NULL printf malloc calloc realloc free memcpy memset stdin stdout stderr"),
  clojure: pack("clojure", "Clojure", "def defn defmacro fn let if do when cond case loop recur quote var throw try catch finally new set! ns in-ns refer require import map reduce filter apply partial comp juxt assoc dissoc conj cons first rest next seq lazy-seq atom swap! reset! future promise keyword symbol vector hash-map #{ -> ->> some->"),
  cpp: pack("cpp", "C++", "alignas alignof and asm auto bitand bool break case catch char class concept const consteval constexpr constinit const_cast continue co_await co_return co_yield decltype default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new noexcept nullptr operator private protected public requires return short signed sizeof static static_assert struct switch template this thread_local throw true try typedef typeid typename union unsigned using virtual void volatile while std:: vector unique_ptr shared_ptr"),
  csharp: pack("csharp", "C#", "abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly record ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while async await var yield LINQ"),
  css: pack("css", "CSS", "align-items animation background border border-radius box-shadow box-sizing color column-gap content cursor display filter flex flex-direction font-family font-size font-weight gap grid grid-template-columns height inset justify-content letter-spacing line-height margin max-width min-height object-fit opacity overflow padding position row-gap text-align text-decoration text-transform transform transition visibility white-space width z-index absolute fixed relative sticky block none inherit initial var(--color) @media @keyframes :hover :focus ::before ::after"),
  dart: pack("dart", "Dart", "abstract as assert async await base break case catch class const continue covariant default deferred do dynamic else enum export extends extension external factory false final finally for Function get hide if implements import in interface is late library mixin new null of on operator part required rethrow return sealed set show static super switch sync this throw true try typedef var void when while with yield Future Stream Widget BuildContext"),
  elixir: pack("elixir", "Elixir", "after alias and case catch cond def defdelegate defexception defguard defimpl defmacro defmodule defp defprotocol defstruct do else end fn for if import in not or quote raise receive require rescue reraise super throw try unless unquote use when with true false nil |> <- => %{} Map Enum String Agent GenServer Task spawn send self"),
  go: pack("go", "Go", "break case chan const continue default defer else fallthrough for func go goto if import interface map package range return select struct switch type var any bool byte complex64 complex128 error float32 float64 int int8 int16 int32 int64 rune string uint uint8 uint16 uint32 uint64 uintptr true false iota nil append cap close copy delete len make new panic print println recover := <-"),
  haskell: pack("haskell", "Haskell", "as case class data default deriving do else family forall foreign hiding if import in infix infixl infixr instance let mdo module newtype of proc qualified rec role then type where _ :: => -> <- <$> <*> >>= pure return fmap foldl foldr map filter Maybe Either Just Nothing Left Right IO String Int Bool True False"),
  html: pack("html", "HTML", "<!DOCTYPE> <html> <head> <body> <main> <header> <footer> <nav> <section> <article> <aside> <div> <span> <p> <a> <button> <form> <input> <label> <select> <option> <textarea> <img> <video> <audio> <canvas> <script> <style> <link> <meta> <title> <h1> <ul> <ol> <li> <table> <thead> <tbody> <tr> <th> <td> class= id= href= src= alt= role= aria-label= data- hidden disabled required tabindex="),
  java: pack("java", "Java", "abstract assert boolean break byte case catch char class const continue default do double else enum exports extends final finally float for goto if implements import instanceof int interface long module native new non-sealed null open opens package permits private protected provides public record requires return sealed short static strictfp super switch synchronized this throw throws to transient transitive try uses var void volatile while with yield true false String Object List Map Optional Stream System.out.println"),
  javascript: pack("javascript", "JavaScript", "as async await break case catch class const continue debugger default delete do else export extends false finally for from function get if import in instanceof let new null of return set static super switch this throw true try typeof undefined var void while with yield => === !== ?. ?? ... Array Object Map Set Promise JSON console.log document window fetch"),
  json: pack("json", "JSON", "{ } [ ] : , true false null \"id\" \"name\" \"type\" \"value\" \"data\" \"items\" \"status\" \"message\" \"error\" \"result\" \"config\" \"version\" \"enabled\" \"createdAt\" \"updatedAt\" \"metadata\" \"properties\" \"required\" \"object\" \"array\" \"string\" \"number\" \"boolean\" \"schemaVersion\" \"description\""),
  julia: pack("julia", "Julia", "baremodule begin break catch const continue do else elseif end export false finally for function global if import let local macro module quote return struct true try using while where mutable primitive abstract type in isa missing nothing Inf NaN Vector Matrix Tuple NamedTuple Dict Set Array broadcast map filter reduce eachindex @time @show :: -> |>"),
  kotlin: pack("kotlin", "Kotlin", "as break class continue do else false for fun if in interface is null object package return super this throw true try typealias typeof val var when while by catch constructor delegate dynamic field file finally get import init param property receiver set setparam where actual abstract annotation companion const crossinline data enum expect external final infix inline inner internal lateinit noinline open operator out override private protected public reified sealed suspend tailrec vararg Unit String Int List Map"),
  lua: pack("lua", "Lua", "and break do else elseif end false for function goto if in local nil not or repeat return then true until while self ... ~= .. # pairs ipairs next type tostring tonumber require pcall xpcall error assert print select setmetatable getmetatable rawget rawset coroutine string table math io os utf8 package"),
  nix: pack("nix", "Nix", "assert else if in inherit let or rec then with builtins import derivation fetchTarball fetchGit map filter foldl' concatMap attrNames attrValues hasAttr getAttr listToAttrs genList length head tail elem elemAt toString fromJSON toJSON readFile pathExists trace abort throw tryEval isAttrs isList isString mkIf mkMerge mkDefault mkForce mkOption mkEnableOption callPackage stdenv writeShellScriptBin nixosSystem homeManagerConfiguration flake inputs outputs packages modules overlays"),
  "objective-c": pack("objective-c", "Objective-C", "@interface @implementation @protocol @end @class @selector @property @synthesize @dynamic @optional @required @autoreleasepool @try @catch @finally @throw @synchronized instancetype id self super nil YES NO Class SEL IMP BOOL NSInteger NSUInteger CGFloat NSString NSArray NSDictionary NSSet NSNumber NSObject alloc init new copy mutableCopy strong weak atomic nonatomic readonly readwrite retain assign IBAction IBOutlet NSLog dispatch_async"),
  ocaml: pack("ocaml", "OCaml", "and as assert begin class constraint do done downto else end exception external false for fun function functor if in include inherit initializer lazy let match method module mutable new nonrec object of open or private rec sig struct then to true try type val virtual when while with mod land lor lxor lsl lsr asr List Array Option Result Some None Ok Error |> @@ ->"),
  perl: pack("perl", "Perl", "__DATA__ __END__ and cmp continue CORE do else elsif eq eval for foreach given goto grep if last local map my ne next no not or our package print q qq qr qw redo require return say state sub tr try unless until use when while xor bless chomp defined delete die exists keys length open push shift splice split sprintf values warn $_ @_ %ENV"),
  php: pack("php", "PHP", "abstract and array as break callable case catch class clone const continue declare default do echo else elseif empty enddeclare endfor endforeach endif endswitch endwhile enum eval exit extends final finally fn for foreach function global goto if implements include include_once instanceof insteadof interface isset list match namespace new or print private protected public readonly require require_once return static switch throw trait try unset use var while xor yield true false null $this => -> ?-> ::"),
  powershell: pack("powershell", "PowerShell", "begin break catch class continue data define do dynamicparam else elseif end enum exit filter finally for foreach from function if in inlinescript parallel param process return sequence switch throw trap try until using var while workflow -and -or -not -eq -ne -gt -ge -lt -le $_ $args $Error $HOME $PSItem Write-Output Get-ChildItem Where-Object ForEach-Object Select-Object Get-Content Set-Content Import-Module Invoke-Command"),
  python: pack("python", "Python", "and as assert async await break case class continue def del elif else except False finally for from global if import in is lambda match None nonlocal not or pass raise return True try while with yield self cls print len range enumerate zip map filter sum min max sorted list dict set tuple str int float bool bytes open super isinstance getattr setattr property staticmethod classmethod dataclass pathlib typing __init__ __name__ ->"),
  r: pack("r", "R", "break else FALSE for function if Inf NA NaN next NULL repeat TRUE while in ... <- -> <<- %>% |> library require data.frame tibble matrix array factor list vector c seq rep length names class typeof str summary head tail subset merge transform aggregate apply lapply sapply vapply map filter select mutate summarise group_by ggplot aes read.csv write.csv set.seed is.na na.omit"),
  ruby: pack("ruby", "Ruby", "BEGIN END alias and begin break case class def defined? do else elsif end ensure false for if in module next nil not or redo rescue retry return self super then true undef unless until when while yield __FILE__ __LINE__ attr_reader attr_writer attr_accessor require include extend private protected public lambda proc block_given? each map select reduce times puts raise freeze symbol Array Hash String Enumerable => &."),
  rust: pack("rust", "Rust", "as async await break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self Self static struct super trait true type unsafe use where while abstract become box do final macro override priv typeof unsized virtual yield try Option Result Some None Ok Err Vec String Box Rc Arc Mutex Iterator IntoIterator println! derive 'static :: => -> ?"),
  scala: pack("scala", "Scala", "abstract case catch class def do else enum export extends false final finally for forSome given if implicit import lazy match new null object opaque open override package private protected return sealed super then this throw trait transparent true try type using val var while with yield Any Nothing Unit Option Some None Either Left Right List Map Set Future synchronized inline derives end => <- _*"),
  solidity: pack("solidity", "Solidity", "abstract address bool break bytes calldata case catch constant constructor continue contract delete do else emit enum error event external fallback false fixed for from function if immutable import indexed interface internal is library mapping memory modifier new override payable pragma private public pure receive return returns revert selfdestruct storage string struct super this throw true try type ufixed uint unchecked using view virtual while wei gwei ether msg.sender msg.value block.timestamp require assert keccak256 abi.encode"),
  sql: pack("sql", "SQL", "ADD ALL ALTER AND ANY AS ASC BACKUP BETWEEN BY CASE CHECK COLUMN CONSTRAINT CREATE DATABASE DEFAULT DELETE DESC DISTINCT DROP ELSE EXISTS FOREIGN FROM FULL GROUP HAVING IN INDEX INNER INSERT INTO IS JOIN KEY LEFT LIKE LIMIT NOT NULL ON OR ORDER OUTER PRIMARY PROCEDURE RIGHT ROWNUM SELECT SET TABLE THEN TOP TRUNCATE UNION UNIQUE UPDATE VALUES VIEW WHEN WHERE WITH COUNT SUM AVG MIN MAX COALESCE CAST OVER PARTITION WINDOW RETURNING"),
  swift: pack("swift", "Swift", "associatedtype class deinit enum extension fileprivate func import init inout internal let open operator private precedencegroup protocol public rethrows static struct subscript typealias var break case catch continue default defer do else fallthrough for guard if in repeat return throw switch where while Any as await false is nil self Self super throws true try async some actor nonisolated weak unowned get set willSet didSet String Int Array Dictionary Optional Result ?? ?. ->"),
  typescript: pack("typescript", "TypeScript", "abstract any as asserts async await bigint boolean break case catch class const constructor continue debugger declare default delete do else enum export extends false finally for from function get if implements import in infer instanceof interface is keyof let module namespace never new null number object of private protected public readonly require return set static string super switch symbol this throw true try type typeof undefined unique unknown var void while with yield satisfies override Record Partial Pick Omit Promise => ?. ??"),
  yaml: pack("yaml", "YAML", "--- ... key: value: name: version: enabled: description: items: metadata: config: services: image: ports: volumes: environment: command: depends_on: build: context: restart: networks: true false null yes no on off | > &anchor *alias !!str !!int !!bool ${VALUE} - [] {} apiVersion: kind: spec: status: labels: annotations:"),
  zig: pack("zig", "Zig", "addrspace align allowzero and anyframe anytype asm async await break catch comptime const continue defer else enum errdefer error export extern false fn for if inline linksection noalias noinline nosuspend null opaque or orelse packed pub resume return struct suspend switch test threadlocal true try union unreachable usingnamespace var volatile while bool usize isize u8 u16 u32 u64 i8 i16 i32 i64 f32 f64 void noreturn undefined @import @intCast @ptrCast @TypeOf .? .* ! ?")
};

function has(id) {
  return typeof id === "string" && Object.prototype.hasOwnProperty.call(PACKS, id);
}

function get(id) {
  const selected = has(id) ? PACKS[id] : PACKS.english;
  return {id: selected.id, label: selected.label, category: selected.category, origin: selected.origin, words: selected.words.slice()};
}

function options() {
  return Object.keys(PACKS).map(function(id) {
    const selected = PACKS[id];
    return {id: selected.id, label: selected.label, category: selected.category, size: selected.words.length};
  });
}

const api = {ORIGIN, has, get, options};
if (typeof module !== "undefined" && module.exports) module.exports = api;
